"""Rick.Fit's icons and link-preview image.

Ricky: "lose the CBK thumbnail for whatsapp shares etc". The site was serving
/icon-192.png and /icon-512.png, which are Coached by Kim's — every share
carried her mark. Drawn here rather than generated by an image model because a
wordmark needs to be exact, repeatable and legible at 32px, which is precisely
what an image model is bad at.

Run: python scripts/make-ricky-brand.py
"""
from PIL import Image, ImageDraw, ImageFont
import os

OUT = os.path.join(os.path.dirname(__file__), '..', 'public', 'brands', 'ricky')
os.makedirs(OUT, exist_ok=True)

BG = (7, 10, 8)
GREEN = (46, 232, 92)
WHITE = (238, 245, 239)
MUTED = (139, 156, 144)

BOLD = 'C:/Windows/Fonts/arialbd.ttf'


def font(size):
    return ImageFont.truetype(BOLD, size)


def centred(draw, box, text, f, fill):
    l, t, r, b = draw.textbbox((0, 0), text, font=f)
    x = box[0] + (box[2] - box[0] - (r - l)) / 2 - l
    y = box[1] + (box[3] - box[1] - (b - t)) / 2 - t
    draw.text((x, y), text, font=f, fill=fill)


def icon(size):
    """A green rounded square with a black R — reads at any size, including the
    16px favicon where anything more detailed turns to mush."""
    im = Image.new('RGB', (size, size), BG)
    d = ImageDraw.Draw(im)
    pad = int(size * 0.09)
    d.rounded_rectangle([pad, pad, size - pad, size - pad],
                        radius=int(size * 0.22), fill=GREEN)
    f = font(int(size * 0.56))
    centred(d, (pad, pad, size - pad, size - pad), 'R', f, BG)
    return im


for s in (192, 512):
    icon(s).save(os.path.join(OUT, f'icon-{s}.png'))
    print(f'icon-{s}.png')

# Link preview: 1200x630 is what WhatsApp, iMessage and the rest crop to.
og = Image.new('RGB', (1200, 630), BG)
d = ImageDraw.Draw(og)

# A slab of green light along the bottom, echoing the app's accent.
for i in range(90):
    a = i / 90
    y = 630 - 90 + i
    d.line([(0, y), (1200, y)],
           fill=(int(BG[0] + (GREEN[0] - BG[0]) * a * 0.85),
                 int(BG[1] + (GREEN[1] - BG[1]) * a * 0.85),
                 int(BG[2] + (GREEN[2] - BG[2]) * a * 0.85)))

mark = icon(150)
og.paste(mark, (90, 150))

d.text((280, 196), 'RICK.FIT', font=font(84), fill=WHITE)
d.text((284, 300), 'Lose the belly fat. Keep the muscle.', font=font(30), fill=GREEN)
d.text((284, 348), 'Training, food and progress in one place.', font=font(26), fill=MUTED)

og.save(os.path.join(OUT, 'og.png'))
print('og.png')
